# Bioinformatics
`Needleman-Wunch Algorithm`

By: `Omar Diab`

In [11]:
import numpy as np
import matplotlib.pyplot as plt

In [12]:
# CONSTANTS: -
"""
My assumptions: -

1: represents a match or a mismatch
2:  represents a vertical gap  |
3: represents a horizontal gap  ---
"""
MISMATCH = -1
MATCH = 2
GAP = -2

In [13]:
def Traceback(decisions_mat,n,m):
    # do an inverse for loop
    i = n-1
    j = m-1
    decisions_list = [] 
    while i >= 0 and j >= 0:
        if decisions_mat[i][j] == 1:
            i -= 1
            j -= 1
            decisions_list.append(1)
        elif decisions_mat[i][j] == 2:
            j -= 1
            decisions_list.append(2)
        elif decisions_mat[i][j] == 3:
            i -= 1
            decisions_list.append(3)

    return decisions_list

In [14]:
delta = lambda x,y,i,j: MATCH if x[i-1] == y[j-1] else MISMATCH

def alignment(x,y):
    m =  len(y)
    n = len(x)
    
    decisions_mat=np.zeros((m,n))
    optimal = np.zeros((m+1,n+1))
    for i in range(1,m+1):
        optimal[i][0] = i*GAP
    
    for j in range(1,n+1):
        optimal[0][j] = j*GAP
    
    for i in range(1,m+1):
        for j in range(1, n+1):
            
            match_mismatch = optimal[i-1][j-1] + delta(x,y,i,j)
            up_gap = optimal[i-1][j] + GAP
            left_gap = optimal[i][j-1] + GAP

            optimal[i][j] = max(match_mismatch, # diagonal
                                left_gap, # left
                                up_gap  # up
                                )
            
            if optimal[i][j] == match_mismatch:
                decisions_mat[i-1][j-1] = 1

            elif optimal[i][j] == left_gap:
                decisions_mat[i-1][j-1] = 2 
                
            elif optimal[i][j] == up_gap:    
                decisions_mat[i-1][j-1] = 3   # up gap
                    
                    
    print("The Alingment Matrix is: ") 
    for row in optimal:
        print(row)
    
    # print("The Decisions Matrix is: ")
    # for row in decisions_mat:
    #     print(row)
    # print("\n")
    decisions_list = Traceback(decisions_mat,n,m)
    return decisions_list

In [15]:
print("The Entered Scoring functions are: - \nMATCH: ",MATCH,"\nMISMATCH: ",MISMATCH,"\nGAP: ",GAP,"\n\n")
y = 'GGTTGACTA'
x = 'TGTTACGGT'
global_alignment_mat = [[],[]]
decisions=alignment(x,y)
m = len(y)
n = len(x)
xi = 0
yi = 0
print("\nTraceBack decisions: - ",decisions)
print("Note: - \n[1]: represents a match or a mismatch/Match, \n[2]: represents a Horizontal gap, \n[3]: represents a vertical gap")

# reverse the decisions list because it was resulted from a traceback algorithm, as i will start from normal index
decisions.reverse() 

for i in decisions:
# if i == 1, then it is a match or a mismatch
    if i == 1:
        global_alignment_mat[0].append(y[yi])
        global_alignment_mat[1].append(x[xi])
        xi += 1
        yi += 1

# if i == 2, then it is a Left gap
    elif i == 2:
        global_alignment_mat[0].append(y[yi])
        global_alignment_mat[1].append("-")
        yi += 1

# if i == 3, then it is a Up gap
    else:    
        global_alignment_mat[0].append("-")
        global_alignment_mat[1].append(x[xi])
        xi += 1

print("\nThe global alignment is: ")
for row in global_alignment_mat:
    print(row)

The Entered Scoring functions are: - 
MATCH:  2 
MISMATCH:  -1 
GAP:  -2 


The Alingment Matrix is: 
[  0.  -2.  -4.  -6.  -8. -10. -12. -14. -16. -18.]
[ -2.  -1.  -3.  -2.  -4.  -6.  -8. -10. -12. -14.]
[ -4.   0.   1.  -1.  -3.  -2.  -4.  -6.  -8. -10.]
[-6. -2. -1.  3.  1. -1. -3. -5. -4. -6.]
[-8. -4. -3.  1.  5.  3.  1. -1. -3. -5.]
[-10.  -6.  -5.  -1.   3.   4.   5.   3.   1.  -1.]
[-12.  -8.  -7.  -3.   1.   2.   3.   7.   5.   3.]
[-14. -10.  -6.  -5.  -1.   3.   1.   5.   6.   4.]
[-16. -12.  -8.  -7.  -3.   1.   2.   3.   4.   5.]
[-18. -14. -10.  -6.  -5.  -1.   0.   1.   5.   3.]

TraceBack decisions: -  [1, 1, 3, 1, 1, 2, 1, 1, 1, 1]
Note: - 
[1]: represents a match or a mismatch/Match, 
[2]: represents a Horizontal gap, 
[3]: represents a vertical gap

The global alignment is: 
['G', 'G', 'T', 'T', 'G', 'A', 'C', '-', 'T', 'A']
['T', 'G', 'T', 'T', '-', 'A', 'C', 'G', 'G', 'T']
